PMS-25-Patient-Detail-UI created patient details UI and modified css in dashboard
Sunilb3/pms pull request #36
Opened 2023-06-06 06:41 UTC by PraveenH18

2023-06-06 07:17 UTC, siddharthp1995 commented on src/view/components/Sidebar/Sidebar.js
> +              <span className="bar"></span>
use react icon instead of three different span

2023-06-06 07:18 UTC, siddharthp1995 commented on src/view/Pages/Patients/patient-details.scss
> +  font-size: 15px;
use rem instead px

2023-06-06 07:18 UTC, siddharthp1995 commented on src/view/Pages/Patients/patient-details.scss
> +  border: 1px solid #ccc;
same rem instead px

2023-06-06 07:19 UTC, siddharthp1995 commented on src/view/Pages/Patients/PatientDetails.js
> +        <div className="edit-modal">
move this edit modal in different component file so that in future we can reuse it for doctor edit modal

2023-06-06 07:20 UTC, siddharthp1995 commented on src/view/Pages/Patients/PatientDetails.js
> +          <div className="right-card">
re write this logic with one flex parent

2023-06-06 07:26 UTC, siddharthp1995 requested changes
few changes as suggested above, and
1) js and scss file name should be same, it can be as per convention either keep Pascal naming format or Camel case. verify it before changing
2) nothing is in px, everything in rem (ex. border 1px should also be in rem)
3) try creating different component or file for different model or functionality. it will look clean, segregate so we can follow SOLID principle design and can reuse it in future

2023-06-06 13:35 UTC, pallawir commented on src/view/Pages/Patients/view/PatientDetails.js
> +    console.log("open modal");
remove console statements

2023-06-08 07:18 UTC, pallawir approved these changes

2023-06-09 07:02 UTC, siddharthp1995 approved these changes

2023-06-09 07:22 UTC, merged